const IntroCard = () => {
    return (
        <>
            <p>
                This app processes csv files generated by{" "}
                <a href="https://www.ixxat.com/products/pc-interfaces-overview/details/usb-to-can-v2-professional">
                    Ixxat's CAN-TO-USB V2
                </a>{" "}
                tool. The tool is used to read the data from the communication occurring in a CAN bus. CAN buses are
                used to connect microcontrollers and other electronic devices in different types of machines which range
                from passenger vehicles, to agricultural equipment, and all the way to 3D printers and lighting control
                systems.
            </p>
            <p>
                The Ixxat CAN-TO-USB V2 tool is just one of the many tools that can read and save the data collected
                from a CAN bus.
            </p>
            <p>This app can only be used to process and summarise csv files collected from that specific tool.</p>
        </>
    );
};

export default IntroCard;
