image: node:18-alpine

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm install
        - CI=false npm run build
    artifacts:
        paths:
            - build/

netlify:
    stage: deploy
    script:
        - npm install -g netlify-cli
        - netlify deploy --dir=build --prod
