image: node:18-alpine

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm install
        - CI=false npm run build
    artifacts:
        paths:
            - build

pages:
    stage: deploy
    dependencies:
        - build
    script:
        - rm -rf public
        - cp build/index.html build/404.html
        - mv build public
    artifacts:
        paths:
            - public
    only:
        - main
